version: '3.7'

networks:
  payment-service:
    driver: ${NETWORKS_DRIVER}

services:
  doc:
    image: payment-service/doc
    build:
      context: .
      dockerfile: ./doc/Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    volumes:
      - "${SERVICE_DIR}/docs:/etc/Sphinx/source"
    ports:
      - "${DOC_PORT}:80"
    networks:
      - payment-service

  mongo:
    image: payment-service/mongo
    container_name: mongo
    build:
      context: .
      dockerfile: ./mongo/Dockerfile
      args:
        MONGO_VERSION: ${MONGO_VERSION}
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - "${SERVICE_DIR}/mongo/data/db:/data/db"
    ports:
      - "${MONGO_PORT}"
    networks:
      - payment-service

  payment:
    image: payment-service/payment
    container_name: payment
    build:
      context: .
      dockerfile: ./payment/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        ENV: ${ENV}
        WORK_DIR: ${WORK_DIR}
    environment:
      - ENV=${ENV}
      - TESTING=${TESTING}
      - DEBUG=${DEBUG}
      - PORT=${PAYMENT_PORT}
      - HOST=${CONTAINER_HOST}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - '${BASE_DIR}:${WORK_DIR}'
    ports:
      - '${PAYMENT_PORT}:${PAYMENT_PORT}'
    networks:
      - payment-service
    